plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version_spec
group = project.mod_group_id

repositories {
	maven { url = "https://api.modrinth.com/maven" }
}

base {
	archivesName = mod_id
}

java {
	withSourcesJar()
	toolchain.languageVersion = JavaLanguageVersion.of(25)
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "maven.modrinth:create-fly:${project.minecraft_version}-rc-2-${project.create_version}"

}

def resourceTargets = [
		minecraft_version      : minecraft_version,
		minecraft_version_range: minecraft_version_range,
		loader_version         : loader_version,
		mod_id                 : mod_id,
		mod_name               : mod_name,
		mod_description        : mod_description,
		mod_license            : mod_license,
		mod_version            : mod_version,
]

processResources {
	inputs.properties(resourceTargets)

	filesMatching("fabric.mod.json") {
		expand resourceTargets
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}
