## Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

## Fabric
minecraft_version=26.2
minecraft_version_range=>=26.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

## Mod Properties
mod_id=cdb
mod_name=Create: Cannon Destroying Block
mod_description=Potato cannon projectiles can now break blocks!
mod_license=GPL-3.0
mod_version=1.0.1
mod_version_spec=1.0.1-26.x-fabric
mod_group_id=com.starman.cdb

create_version=6.0.9-1